baseurl: "/"
title: "SGDS"
params:
  logo: logo_sgds.png
  docs_url: 'https://docs.stackbit.com'
menus:
  main:
    - identifier: home
      weight: 1
      url: /
      title: Home
  secondary:
    - identifier: about
      weight: 1
      url: about
      title: About
sass:
  input_file: sass/main.scss.njk
  output_file: css/sgds.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
